spring:
  application:
    name: ingsoft
  datasource:
    name: db_covid19
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_covid19?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ""
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000

  batch:
    job:
      enabled=false:server:
  error:
    include-message: always
logging:
  level:
    com:
      spring:
        ibatis:
          UserMapper=DEBUG:
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/dao/*Dao.xml

