GET http://localhost:8080/city/statistics/1?date=2021-05-30
Accept: application/json
Content-Type: application/json
###

### Mostrar proyecciones por metodo de minimos cuadrados de datos de una ciudad desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/city/leastSquaresAllInfo/1/2021-05-30
Accept: application/json
Content-Type: application/json
###

### Mostrar proyecciones por metodo de incremento absoluto de datos de una ciudad desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/city/absoluteIncreaseAllInfo/1/2021-05-30
Accept: application/json
Content-Type: application/json
###
### Mostrar proyecciones por metodo del incremento porcentual de datos de una ciudad desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/city/percentageIncreaseAllInfo/1/2021-05-30
Accept: application/json
Content-Type: application/json
###

### Mostrar proyecciones por el modelo de Brwon de datos de una ciudad desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/city/brownModelAllInfo/1/2021-05-30
Accept: application/json
Content-Type: application/json
###