### Obtiene la informacion de los datos del COVID-19 de una ciudad al recibir el Id y la fecha

GET http://localhost:8080/city/1?date=2021-04-14
Accept: application/json
Content-Type: application/json

### Obtiene la informacion de los datos del COVID-19 de todos los departamentos al recibir la fecha

GET http://localhost:8080/city?date=2021-04-04
Accept: application/json
Content-Type: application/json
### Obtiene la informacion de los datos del COVID-19 de una ciudad al recibir el Id y la fecha

GET http://localhost:8080/city/allInfo/1?date=2021-05-23
Accept: application/json
Content-Type: application/json

