
GET http://localhost:8080/city
Accept: application/json
Content-Type: application/json


###
GET http://localhost:8080/city/location
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/city/1/2021-04-14
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/city/2021-04-04
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/city/name/Tarija/municipality/2021-05-17
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/city/1/municipality/2021-05-17
Accept: application/json
Content-Type: application/json