### Obtiene la informacion de los datos del COVID-19 de un pais al recibir el Id del pais y la fecha

GET http://localhost:8080/country/1?date=2021-05-11
Accept: application/json
Content-Type: application/json

###
## Mostrar covid data de un pais desde el inicio de los datos hasta la fecha indicada
GET http://localhost:8080/country/allInfo/1?date=2021-5-19
Accept: application/json
Content-Type: application/json

