
GET http://localhost:8080/country/location
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/country/1/2021-05-11
Accept: application/json
Content-Type: application/json

###