
POST http://localhost:8080/drugstore
Accept: application/json
Content-Type: application/json

{
  "idCity": 1,
  "name": "Farmacia Chavez",
  "lon": -68.12027017331768,
  "lat": -16.483746282554062

}

###

GET http://localhost:8080/drugstore/locations
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/drugstore/location/1
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/drugstore/location/city/1
Accept: application/json
Content-Type: application/json

###

DELETE http://localhost:8080/drugstore/deleteDrugstore?drugstoreId=2
Accept: application/json
Content-Type: application/json
