## Obtiene las locaciones de un hospital
GET http://localhost:8080/hospital/location/2
Accept: application/json
Content-Type: application/json

###
## Obtiene las locaciones de todos los hospitales
GET http://localhost:8080/hospital/locations
Accept: application/json
Content-Type: application/json

###
## Obtiene la informacion de todos los hospitales
GET http://localhost:8080/hospital/allInfo?n=10&i=0
Accept: application/json
Content-Type: application/json

###
##Obtiene las locaciones de hospitales de una ciudad
GET http://localhost:8080/hospital/locationsByCity/1
Accept: application/json
Content-Type: application/json

###
##Agrega los datos de un hospital
POST http://localhost:8080/hospital/addHospital
Accept: application/json
Content-Type: application/json

{
  "idCity": 1,
  "name": "Hospital de Clinicas",
  "lon": -68.1186046495648,
  "lat": -16.50703525
}

###
##Elimina los datos de un hospital
PUT http://localhost:8080/hospital/deleteHospital
Accept: application/json
Content-Type: application/json

{
  "idHospital": 1
}

###
##Actualiza los datos de un hospital
PUT http://localhost:8080/hospital/updateHospital
Accept: application/json
Content-Type: application/json

{
  "idHospital": 2,
  "idCity": 2,
  "name": "Hospital del Niño",
  "lon": -100.3699597,
  "lat": 20.5776891
}