## Obtiene las locaciones de un hospital
GET http://localhost:8080/hospital/location/2
Accept: application/json
Content-Type: application/json

###
## Obtiene las locaciones de todos los hospitales
GET http://localhost:8080/hospital/locations
Accept: application/json
Content-Type: application/json

###
## Obtiene la informacion de todos los hospitales
GET http://localhost:8080/hospital/allInfo?n=10&i=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJwb21hYWx2aW5AZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImFkbWluSWQiOjIsImV4cCI6MTYyMTI4Mjc2MywidXNlck5hbWUiOiJBbHZpbiBKYW1pbCIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiMGUxNTgwZTUtMWJiNi00ZTNhLThhOTctZTlkMjQwZTYxZWE4IiwiZW1haWwiOiJwb21hYWx2aW5AZ21haWwuY29tIiwiY2xpZW50X2lkIjoiY292aWQxOXByb3llY3QifQ.QoXjSaHZ3pT0RgXabdivqmzxJZ-pYLbZ-3dDK9kmpCs
Accept: application/json
Content-Type: application/json

###
##Obtiene las locaciones de hospitales de una ciudad
GET http://localhost:8080/hospital/locations?cityId=1
Accept: application/json
Content-Type: application/json

###
##Agrega los datos de un hospital
POST http://localhost:8080/hospital
Accept: application/json
Content-Type: application/json

{
  "idCity": 1,
  "name": "Hospital de Clinicas",
  "lon": -68.1186046495648,
  "lat": -16.50703525
}

###
##Elimina los datos de un hospital
DELETE http://localhost:8080/hospital?hospitalId=1
Accept: application/json
Content-Type: application/json

{
  "idHospital": 1
}

###
##Actualiza los datos de un hospital
PUT http://localhost:8080/hospital
Accept: application/json
Content-Type: application/json

{
  "idHospital": 2,
  "idCity": 2,
  "name": "Hospital del Niño",
  "lon": -100.3699597,
  "lat": 20.5776891
}