## Mostrar covid data de un municipio desde el inicio de los datos hasta la fecha indicada
GET http://localhost:8080/municipality/allInfo/8/2021-04-29
Accept: application/json
Content-Type: application/json

### Mostrar media de datos de un municipio desde el inicio de los datos hasta la fecha indicada
### Si no existen datos de casos de muerte, casos confirmados, vacunados o recuperados, la media es 0.

GET http://localhost:8080/municipality/mediaAllInfo/8/2021-04-29
Accept: application/json
Content-Type: application/json

### Mostrar varianza de datos de un municipio desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/municipality/varianceAllInfo/1/2021-05-19
Accept: application/json
Content-Type: application/json

### Mostrar Intervalo de confianza de datos de un municipio desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/municipality/confidenceIntervalAllInfo/1/2021-05-19
Accept: application/json
Content-Type: application/json

### Mostrar proyecciones por metodo de minimos cuadrados de datos de un municipio desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/municipality/leastSquaresAllInfo/1/2021-5-29/2021-05-30
Accept: application/json
Content-Type: application/json
###

### Mostrar proyecciones por metodo de incremento absoluto de datos de un municipio desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/municipality/absoluteIncreaseAllInfo/1
Accept: application/json
Content-Type: application/json
###