
### Obtener todas las localizaciones de los municipios en una lista
GET http://localhost:8080/municipality/locations?cityId=1
Accept: application/json
Content-Type: application/json


### Obtener la informacion de un municipio al recibir el municipio y la ultima fecha
GET http://localhost:8080/municipality/4/2021-04-15
Accept: application/json
Content-Type: application/json

### Obtener todas los datos de los municipios sobre una fecha o la fecha que se acerca mas los datos
GET http://localhost:8080/municipality/2021-04-14
Accept: application/json
Content-Type: application/json
###

### Obtener la informacion de un municipio al recibir el municipio y la ultima fecha
GET http://localhost:8080/municipality/allInfo/4?date=2021-04-1
Accept: application/json
Content-Type: application/json

### Obtiene la informacion de los datos del COVID-19 de todos los municipios de un departamentos al recibir el Id de la ciudad y la fecha

GET http://localhost:8080/municipality?dateCovid=2021-05-21&cityId=7
Accept: application/json
Content-Type: application/json