GET http://localhost:8080/municipality/statistics/1?date=2021-05-30
Accept: application/json
Content-Type: application/json
###
### Mostrar proyecciones por metodo de minimos cuadrados de datos de un municipio desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/municipality/leastSquaresAllInfo/1/2021-05-30
Accept: application/json
Content-Type: application/json
###

### Mostrar proyecciones por metodo de incremento absoluto de datos de un municipio desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/municipality/absoluteIncreaseAllInfo/1
Accept: application/json
Content-Type: application/json
###
### Mostrar proyecciones por metodo del incremento porcentual de datos de un municipio desde el inicio de los datos hasta la fecha indicada

GET http://localhost:8080/municipality/percentageIncreaseAllInfo/1/2021-05-30
Accept: application/json
Content-Type: application/json
###