
GET http://localhost:8080/municipality/location/1
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/municipality/1/2021-04-02
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/municipality/2021-04-14
Accept: application/json
Content-Type: application/json

###