## Mostrar covid data de un municipio desde el inicio de los datos hasta la fecha indicada
GET http://192.168.31.150:8080/municipality/allInfo/1/2021-04-05
Accept: application/json
Content-Type: application/json


###