## Mostrar covid data de un municipio desde el inicio de los datos hasta la fecha indicada
GET http://localhost:8080/municipality/allInfo/1?date=2021-04-29
Accept: application/json
Content-Type: application/json
