### Obtiene la informacion de todas las noticias en la BD

GET http://localhost:8080/news/list
Accept: application/json
Content-Type: application/json

### Crea una noticia a la Bd

POST http://localhost:8080/news/addNews
Accept: application/json
Content-Type: application/json

{
  "title": "Viene tercera ola",
  "content": "Basado en la cantidad de los ultimos casos se puede confirmar la llegada de una tercera ola de contagios",
  "dateNews": "2021-04-18",
  "newsImages": "",
  "newsUrl": "https://s.france24.com/media/display/bb75a678-973a-11eb-867f-005056bff430/w:980/p:16x9/vacunas%20bolivia.webp"
}

### Elimina la informacion de una noticia
DELETE http://localhost:8080/news/delete/3
Accept: application/json

### Actualiza la informacion de una noticia
PUT http://localhost:8080/news/updateNews
Accept: application/json
Content-Type: application/json

{
  "idNews": 10,
  "title": "Viene tercera ola",
  "content": "Basado en la cantidad de los ultimos casos se puede confirmar la llegada de una tercera ola de contagios",
  "dateNews": "2021-05-12",
  "newsImages": "",
  "newsUrl": "https://s.france24.com/media/display/bb75a678-973a-11eb-867f-005056bff430/w:980/p:16x9/vacunas%20bolivia.webp"
}