### getting the list of news

GET http://localhost:8080/news/list?n=10&i=0
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJlcndpbkBnbWFpbC5jb20iLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiYWRtaW5JZCI6MSwiZXhwIjoxNjIxNDQ4NjI4LCJ1c2VyTmFtZSI6ImVyd2luIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiI3NmNmYmViMy1hMzUwLTRiOWYtYjQ3Yy03NTQ1NTFhNzIzOGQiLCJlbWFpbCI6ImVyd2luQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6ImNvdmlkMTlwcm95ZWN0In0.mygMf-6fSFKh5LK3XC74RVGbK-4UyX2HuKO2YjUf9kE

### adding a new news

POST http://localhost:8080/news/addNews
Accept: application/json
Content-Type: application/json

{
  "title": "Viene tercera ola",
  "content": "Basado en la cantidad de los ultimos casos se puede confirmar la llegada de una tercera ola de contagios",
  "dateNews": "2021-04-18",
  "newsImages": "",
  "newsUrl": "https://s.france24.com/media/display/bb75a678-973a-11eb-867f-005056bff430/w:980/p:16x9/vacunas%20bolivia.webp"
}

### delete news
DELETE http://localhost:8080/news/delete/3
Accept: application/json

### delete news
PUT http://localhost:8080/news/updateNews
Accept: application/json
Content-Type: application/json

{
  "idNews": 10,
  "title": "Viene tercera ola",
  "content": "Basado en la cantidad de los ultimos casos se puede confirmar la llegada de una tercera ola de contagios",
  "dateNews": "2021-05-12",
  "newsImages": "",
  "newsUrl": "https://s.france24.com/media/display/bb75a678-973a-11eb-867f-005056bff430/w:980/p:16x9/vacunas%20bolivia.webp"
}